import pandas as pd

tech_stores = [
    "TechHive", "GizmoGalaxy", "ByteBazaar", "CircuitCentral", "GadgetGarage", "DigitalDen", 
    "PixelPoint", "ElectroEmporium", "CodeCave", "QuantumQuest", "TechTopia", "NanoNest",
    "CyberCorner", "LogicLab", "ChipChamber", "FutureFusion", "ByteBoutique", "GadgetGrove",
    "CircuitCity", "MegaMatrix", "QuantumQuarters", "ElectroEdge", "PixelPalace", "TechTemple",
    "CodeCrafters", "DigitalDomain", "NanoNook", "CyberSphere", "GizmoGarden", "TechTrove",
    "ByteBarn", "CircuitCove", "PixelPavilion", "ElectroEden", "QuantumQuotient", "GadgetGallery",
    "CodeCastle", "DigitalDepot", "NanoNation", "TechTerrace", "CyberCove", "ElectroExhibit",
    "GizmoGallery", "PixelPlace", "CircuitCabin", "ByteBazaar", "QuantumQuadrant", "TechTower",
    "LogicLounge", "ChipChalet", "ElectroEmporium", "DigitalDome", "NanoNexus", "CyberCitadel",
    "GadgetGalleria", "TechTraders", "PixelPlaza", "ByteBoutique", "QuantumQuarter", "CodeCave",
    "CircuitCorner", "GizmoGrounds", "DigitalDen", "ElectroEdge", "TechTopia", "NanoNiche",
    "CyberCrafters", "PixelPlex", "ChipCenter", "GadgetGarage", "QuantumQuest", "ByteBarn",
    "TechTrove", "LogicLab", "CircuitCity", "ElectroEden", "CodeCastle", "DigitalDomain",
    "NanoNest", "CyberSphere", "GizmoGarden", "PixelPoint", "TechTemple", "ElectroEmporium",
    "QuantumQuotient", "ByteBazaar", "GadgetGallery", "CircuitCabin", "DigitalDepot",
    "NanoNation", "TechTerrace", "CyberCove", "PixelPavilion", "LogicLounge", "ChipChamber",
    "ElectroExhibit", "GizmoGallery", "TechTraders", "PixelPlaza", "ByteBoutique",
    "QuantumQuadrant", "CodeCrafters", "CircuitCorner", "GadgetGrove", "DigitalDome",
    "NanoNexus", "CyberCitadel", "TechTower", "PixelPlace", "ElectroEdge", "LogicLab",
    "ChipChalet", "ByteBarn", "GadgetGarage", "QuantumQuest", "DigitalDen", "TechTrove",
    "NanoNiche", "CyberCrafters", "PixelPlex", "CircuitCity", "CodeCastle", "ElectroEden",
    "GizmoGarden", "TechTemple", "ByteBazaar", "QuantumQuotient", "DigitalDomain",
    "GadgetGallery", "CircuitCabin", "NanoNest", "TechTerrace", "CyberCove", "PixelPavilion",
    "LogicLounge", "ChipCenter", "ElectroEmporium", "GizmoGallery", "TechTraders",
    "PixelPlaza", "ByteBoutique", "QuantumQuarter", "CodeCave", "CircuitCorner", "GadgetGrove",
    "DigitalDome", "NanoNexus", "CyberCitadel", "TechTower", "PixelPlace", "ElectroEdge",
    "LogicLab", "ChipChalet", "ByteBarn", "GadgetGarage", "QuantumQuest", "DigitalDen",
    "TechTrove", "NanoNiche", "CyberCrafters", "PixelPlex", "CircuitCity", "CodeCastle",
    "ElectroEden", "GizmoGarden", "TechTemple", "ByteBazaar", "QuantumQuotient", "DigitalDomain",
    "GadgetGallery", "CircuitCabin", "NanoNest", "TechTerrace", "CyberCove", "PixelPavilion",
    "LogicLounge", "ChipCenter", "ElectroEmporium", "GizmoGallery", "TechTraders", "PixelPlaza",
    "ByteBoutique", "QuantumQuadrant", "CodeCrafters", "CircuitCorner", "GadgetGrove",
    "DigitalDome", "NanoNexus", "CyberCitadel", "TechTower", "PixelPlace", "ElectroEdge",
    "LogicLab", "ChipChalet", "ByteBarn", "GadgetGarage", "QuantumQuest", "DigitalDen",
    "TechTrove", "NanoNiche", "CyberCrafters", "PixelPlex", "CircuitCity", "CodeCastle",
    "ElectroEden", "GizmoGarden", "TechTemple", "ByteBazaar", "QuantumQuotient", "DigitalDomain",
    "GadgetGallery", "CircuitCabin", "NanoNest", "TechTerrace", "CyberCove", "PixelPavilion",
    "LogicLounge", "ChipCenter", "ElectroEmporium", "GizmoGallery", "TechTraders", "PixelPlaza",
    "ByteBoutique", "QuantumQuarter", "CodeCave", "CircuitCorner", "GadgetGrove", "DigitalDome",
    "NanoNexus", "CyberCitadel", "TechTower", "PixelPlace", "ElectroEdge", "LogicLab", "ChipChalet",
    "ByteBarn", "GadgetGarage", "QuantumQuest", "DigitalDen", "TechTrove", "NanoNiche",
    "CyberCrafters", "PixelPlex", "CircuitCity", "CodeCastle", "ElectroEden", "GizmoGarden",
    "TechTemple", "ByteBazaar", "QuantumQuotient", "DigitalDomain", "GadgetGallery", "CircuitCabin",
    "NanoNest", "TechTerrace", "CyberCove", "PixelPavilion", "LogicLounge", "ChipCenter",
    "ElectroEmporium", "GizmoGallery", "TechTraders", "PixelPlaza", "ByteBoutique", "QuantumQuadrant",
    "CodeCrafters", "CircuitCorner", "GadgetGrove", "DigitalDome", "NanoNexus", "CyberCitadel",
    "TechTower", "PixelPlace", "ElectroEdge", "LogicLab", "ChipChalet", "ByteBarn", "GadgetGarage",
    "QuantumQuest", "DigitalDen", "TechTrove", "NanoNiche", "CyberCrafters", "PixelPlex",
    "CircuitCity", "CodeCastle", "ElectroEden", "GizmoGarden", "TechTemple", "ByteBazaar",
    "QuantumQuotient", "DigitalDomain", "GadgetGallery", "CircuitCabin", "NanoNest", "TechTerrace",
    "CyberCove", "PixelPavilion", "LogicLounge", "ChipCenter", "ElectroEmporium", "GizmoGallery",
    "TechTraders", "PixelPlaza", "ByteBoutique", "QuantumQuarter", "CodeCave", "CircuitCorner",
    "GadgetGrove", "DigitalDome", "NanoNexus", "CyberCitadel", "TechTower", "PixelPlace", "ElectroEdge",
    "LogicLab", "ChipChalet", "ByteBarn", "GadgetGarage", "QuantumQuest", "DigitalDen", "TechTrove",
    "NanoNiche", "CyberCrafters", "PixelPlex", "CircuitCity", "CodeCastle", "ElectroEden",
    "GizmoGarden", "TechTemple", "ByteBazaar", "QuantumQuotient", "DigitalDomain", "GadgetGallery",
    "CircuitCabin", "NanoNest", "TechTerrace", "CyberCove", "PixelPavilion", "LogicLounge",
    "ChipCenter", "ElectroEmporium", "GizmoGallery", "TechTraders", "PixelPlaza", "ByteBoutique",
    "QuantumQuadrant", "CodeCrafters", "CircuitCorner", "GadgetGrove", "DigitalDome", "NanoNexus",
    "CyberCitadel", "TechTower", "PixelPlace", "ElectroEdge", "LogicLab", "ChipChalet", "ByteBarn",
    "GadgetGarage", "QuantumQuest", "DigitalDen", "TechTrove", "NanoNiche", "CyberCrafters",
    "PixelPlex", "CircuitCity", "CodeCastle", "ElectroEden", "GizmoGarden", "TechTemple",
    "ByteBazaar", "QuantumQuotient", "DigitalDomain", "GadgetGallery", "CircuitCabin", "NanoNest",
    "TechTerrace", "CyberCove", "PixelPavilion", "LogicLounge", "ChipCenter", "ElectroEmporium",
    "GizmoGallery", "TechTraders", "PixelPlaza", "ByteBoutique", "QuantumQuarter", "CodeCave",
    "CircuitCorner", "GadgetGrove", "DigitalDome", "NanoNexus", "CyberCitadel", "TechTower",
    "PixelPlace", "ElectroEdge", "LogicLab", "ChipChalet", "ByteBarn", "GadgetGarage", "QuantumQuest",
    "DigitalDen", "TechTrove", "NanoNiche", "CyberCrafters", "PixelPlex", "CircuitCity", "CodeCastle",
    "ElectroEden", "GizmoGarden", "TechTemple", "ByteBazaar", "QuantumQuotient", "DigitalDomain",
    "GadgetGallery", "CircuitCabin", "NanoNest", "TechTerrace", "CyberCove", "PixelPavilion",
    "LogicLounge", "ChipCenter", "ElectroEmporium", "GizmoGallery", "TechTraders", "PixelPlaza",
    "ByteBoutique", "QuantumQuadrant", "CodeCrafters", "CircuitCorner", "GadgetGrove", "DigitalDome",
    "NanoNexus", "CyberCitadel", "TechTower", "PixelPlace", "ElectroEdge", "LogicLab", "ChipChalet",
    "ByteBarn", "GadgetGarage", "QuantumQuest", "DigitalDen", "TechTrove", "NanoNiche", "CyberCrafters",
    "PixelPlex", "CircuitCity", "CodeCastle", "ElectroEden", "GizmoGarden", "TechTemple",
    "ByteBazaar", "QuantumQuotient", "DigitalDomain", "GadgetGallery", "CircuitCabin", "NanoNest",
    "TechTerrace", "CyberCove", "PixelPavilion", "LogicLounge", "ChipCenter", "ElectroEmporium",
    "GizmoGallery", "TechTraders", "PixelPlaza", "ByteBoutique", "QuantumQuarter", "CodeCave",
    "CircuitCorner", "GadgetGrove", "DigitalDome", "NanoNexus", "CyberCitadel", "TechTower",
    "PixelPlace", "ElectroEdge", "LogicLab", "ChipChalet", "ByteBarn", "GadgetGarage", "QuantumQuest",
    "DigitalDen", "TechTrove", "NanoNiche", "CyberCrafters", "PixelPlex", "CircuitCity", "CodeCastle",
    "ElectroEden", "GizmoGarden", "TechTemple", "ByteBazaar", "QuantumQuotient", "DigitalDomain",
    "GadgetGallery", "CircuitCabin", "NanoNest", "TechTerrace", "CyberCove", "PixelPavilion"
]


clothing_stores = [
    "FashionFront", "StyleStreet", "WardrobeWorks", "TrendTower", "ChicCorner", "VogueVault",
    "ClothCove", "ApparelArena", "GarmentGallery", "ModishMarket", "ThreadThrive", "OutfitOasis",
    "CoutureCorner", "DressDomain", "FashionFoyer", "TrendTerrace", "StyleSanctuary", "WearWave",
    "ChicChamber", "WardrobeWay", "ApparelAlcove", "GlamGrove", "ClothingCabin", "VogueVista",
    "ModMode", "ThreadThicket", "FashionFactory", "StyleSpot", "CoutureCrest", "GarmentGrove",
    "TrendTreat", "WardrobeWagon", "ChicCastle", "DressDome", "ApparelAvenue", "ClothCastle",
    "OutfitOutpost", "FashionFountain", "StyleSphere", "ThreadTower", "GlamGallery", "WearWard",
    "WardrobeWharf", "VogueVine", "ClothingCrafters", "TrendTrove", "ChicChalet", "CoutureCave",
    "FashionField", "ApparelAlley", "StyleStation", "DressDepot", "GlamGrounds", "WardrobeWing",
    "ModishMeadow", "ThreadTrail", "FashionFiesta", "TrendTrail", "StyleStreetwear", "VogueVaults",
    "ChicChannel", "WardrobeWorkshop", "ApparelArcade", "GlamGalleria", "ClothingCove", "FashionFinds",
    "ThreadThrift", "CoutureCourt", "DressDen", "TrendTemple", "StyleSanctum", "WardrobeWonders",
    "ChicChamberlain", "ApparelAtrium", "FashionFrontier", "GarmentGalleria", "OutfitOasis", "ClothCrafters",
    "TrendTide", "VogueVistaPoint", "FashionFacet", "StyleSalon", "WardrobeWhimsy", "CoutureColony",
    "ThreadTreasure", "GlamGrovePlace", "DressDistrict", "ApparelAlcazar", "ChicChateau", "WardrobeWick",
    "FashionFables", "StyleStreetwearHub", "TrendTreats", "CoutureCove", "ClothingCorner", "GlamGarb",
    "ThreadThrone", "WardrobeWarden", "ModishManor", "OutfitOvation", "FashionFrontline", "StyleStall",
    "DressDazzle", "WardrobeWondershop", "CoutureCabana", "TrendTroveHub", "ChicCrescent", "ApparelAisle",
    "FashionFling", "GlamGleam", "ThreadThread", "ClothingCastle", "VogueVanguard", "WardrobeWingman",
    "StyleSilo", "DressDock", "CoutureCluster", "ApparelAlcoveHub", "TrendTowerHub", "FashionFleet",
    "ChicChime", "WardrobeWayfarer", "ThreadThriveHub", "OutfitOutlet", "GlamGalleriaHub", "StyleSanctumSpot",
    "FashionFusion", "ClothingCoveHub", "DressDenHub", "WardrobeWharfHub", "CoutureCrestHub", "TrendTreatsHub",
    "ThreadThicketHub", "VogueVaultHub", "ModishMarketHub", "ChicCornerHub", "FashionFoyerHub", "ApparelArenaHub",
    "WardrobeWorksHub", "StyleStreetHub", "GlamGroundsHub", "ClothCoveHub", "OutfitOasisHub", "DressDomainHub",
    "CoutureCornerHub", "TrendTerraceHub", "FashionFrontHub", "WardrobeWayHub", "ChicChamberHub", "ApparelAlcoveHub",
    "WearWaveHub", "ThreadTowerHub", "ModModeHub", "StyleSpotHub", "GlamGalleryHub", "FashionFactoryHub",
    "ClothingCabinHub", "WardrobeWharfHub", "TrendTroveHub", "VogueVistaHub", "FashionFiestaHub", "ChicChannelHub",
    "DressDepotHub", "GlamGrovePlaceHub", "WardrobeWingHub", "ModishMeadowHub", "ThreadTrailHub", "StyleStationHub",
    "ApparelArcadeHub", "FashionFieldHub", "CoutureCaveHub", "ClothCastleHub", "OutfitOutpostHub", "GlamGalleriaHub",
    "WardrobeWagonHub", "TrendTempleHub", "StyleSanctuaryHub", "FashionFountainHub", "ThreadThriftHub", "CoutureCourtHub",
    "WardrobeWondersHub", "ChicChaletHub", "FashionFablesHub", "ApparelAtriumHub", "StyleSalonHub", "GlamGarbHub",
    "ThreadTreasureHub", "DressDistrictHub", "CoutureColonyHub", "OutfitOvationHub", "FashionFrontlineHub", "StyleStallHub",
    "WardrobeWhimsyHub", "TrendTideHub", "ClothingCraftersHub", "FashionFacetHub", "VogueVineHub", "DressDazzleHub",
    "WardrobeWardenHub", "ModishManorHub", "ApparelAisleHub", "FashionFlingHub", "GlamGleamHub", "WardrobeWingmanHub",
    "ThreadThreadHub", "VogueVanguardHub", "StyleSiloHub", "DressDockHub", "CoutureClusterHub", "TrendTowerHub",
    "FashionFleetHub", "ChicChimeHub", "WardrobeWayfarerHub", "ThreadThriveHub", "OutfitOutletHub", "GlamGalleriaHub",
    "StyleSanctumSpotHub", "FashionFusionHub", "ClothingCoveHub", "DressDenHub", "WardrobeWharfHub", "CoutureCrestHub",
    "TrendTreatsHub", "ThreadThicketHub", "VogueVaultHub", "ModishMarketHub", "ChicCornerHub", "FashionFoyerHub",
    "ApparelArenaHub", "WardrobeWorksHub", "StyleStreetHub", "GlamGroundsHub", "ClothCoveHub", "OutfitOasisHub",
    "DressDomainHub", "CoutureCornerHub", "TrendTerraceHub", "FashionFrontHub", "WardrobeWayHub", "ChicChamberHub",
    "ApparelAlcoveHub", "WearWaveHub", "ThreadTowerHub", "ModModeHub", "StyleSpotHub", "GlamGalleryHub", "FashionFactoryHub",
    "ClothingCabinHub", "WardrobeWharfHub", "TrendTroveHub", "VogueVistaHub", "FashionFiestaHub", "ChicChannelHub",
    "DressDepotHub", "GlamGrovePlaceHub", "WardrobeWingHub", "ModishMeadowHub", "ThreadTrailHub", "StyleStationHub",
    "ApparelArcadeHub", "FashionFieldHub", "CoutureCaveHub", "ClothCastleHub", "OutfitOutpostHub", "GlamGalleriaHub",
    "WardrobeWagonHub", "TrendTempleHub", "StyleSanctuaryHub", "FashionFountainHub", "ThreadThriftHub", "CoutureCourtHub",
    "WardrobeWondersHub", "ChicChaletHub", "FashionFablesHub", "ApparelAtriumHub", "StyleSalonHub", "GlamGarbHub",
    "ThreadTreasureHub", "DressDistrictHub", "CoutureColonyHub", "OutfitOvationHub", "FashionFrontlineHub", "StyleStallHub",
    "WardrobeWhimsyHub", "TrendTideHub", "ClothingCraftersHub", "FashionFacetHub", "VogueVineHub", "DressDazzleHub",
    "WardrobeWardenHub", "ModishManorHub", "ApparelAisleHub", "FashionFlingHub", "GlamGleamHub", "WardrobeWingmanHub",
    "ThreadThreadHub", "VogueVanguardHub", "StyleSiloHub", "DressDockHub", "CoutureClusterHub", "TrendTowerHub",
    "FashionFleetHub", "ChicChimeHub", "WardrobeWayfarerHub", "ThreadThriveHub", "OutfitOutletHub", "GlamGalleriaHub",
    "StyleSanctumSpotHub", "FashionFusionHub", "ClothingCoveHub", "DressDenHub", "WardrobeWharfHub", "CoutureCrestHub",
    "TrendTreatsHub", "ThreadThicketHub", "VogueVaultHub", "ModishMarketHub", "ChicCornerHub", "FashionFoyerHub",
    "ApparelArenaHub", "WardrobeWorksHub", "StyleStreetHub", "GlamGroundsHub", "ClothCoveHub", "OutfitOasisHub",
    "DressDomainHub", "CoutureCornerHub", "TrendTerraceHub", "FashionFrontHub", "WardrobeWayHub", "ChicChamberHub",
    "ApparelAlcoveHub", "WearWaveHub", "ThreadTowerHub", "ModModeHub", "StyleSpotHub", "GlamGalleryHub", "FashionFactoryHub",
    "ClothingCabinHub", "WardrobeWharfHub", "TrendTroveHub", "VogueVistaHub", "FashionFiestaHub", "ChicChannelHub",
    "DressDepotHub", "GlamGrovePlaceHub", "WardrobeWingHub", "ModishMeadowHub", "ThreadTrailHub", "StyleStationHub",
    "ApparelArcadeHub", "FashionFieldHub", "CoutureCaveHub", "ClothCastleHub", "OutfitOutpostHub", "GlamGalleriaHub",
    "WardrobeWagonHub", "TrendTempleHub", "StyleSanctuaryHub", "FashionFountainHub", "ThreadThriftHub", "CoutureCourtHub",
    "WardrobeWondersHub", "ChicChaletHub", "FashionFablesHub", "ApparelAtriumHub", "StyleSalonHub", "GlamGarbHub",
    "ThreadTreasureHub", "DressDistrictHub", "CoutureColonyHub", "OutfitOvationHub", "FashionFrontlineHub", "StyleStallHub",
    "WardrobeWhimsyHub", "TrendTideHub", "ClothingCraftersHub", "FashionFacetHub", "VogueVineHub", "DressDazzleHub",
    "WardrobeWardenHub", "ModishManorHub", "ApparelAisleHub", "FashionFlingHub", "GlamGleamHub", "WardrobeWingmanHub",
    "ThreadThreadHub", "VogueVanguardHub", "StyleSiloHub", "DressDockHub", "CoutureClusterHub", "TrendTowerHub",
    "FashionFleetHub", "ChicChimeHub", "WardrobeWayfarerHub", "ThreadThriveHub", "OutfitOutletHub", "GlamGalleriaHub",
    "StyleSanctumSpotHub", "FashionFusionHub", "ClothingCoveHub", "DressDenHub", "WardrobeWharfHub", "CoutureCrestHub",
    "TrendTreatsHub", "ThreadThicketHub", "VogueVaultHub", "ModishMarketHub", "ChicCornerHub", "FashionFoyerHub",
    "ApparelArenaHub", "WardrobeWorksHub", "StyleStreetHub", "GlamGroundsHub", "ClothCoveHub", "OutfitOasisHub",
    "DressDomainHub", "CoutureCornerHub", "TrendTerraceHub", "FashionFrontHub", "WardrobeWayHub", "ChicChamberHub",
    "ApparelAlcoveHub", "WearWaveHub", "ThreadTowerHub", "ModModeHub", "StyleSpotHub", "GlamGalleryHub", "FashionFactoryHub"
]


def generate_stores_schema():
    adventure_works_stores = pd.read_csv('data/input/stores.csv')

    stores_names = list(adventure_works_stores['storeName']) + tech_stores + clothing_stores
    stores = [{ 'id': i, 'name': s} for i, s in enumerate(stores_names, start=1)]

    # Add AdventureWorks itself as a store for customers that bought directly from the source   
    stores.append({ 'id': len(stores) + 1, 'name': 'AdventureWorks'})

    stores_df = pd.DataFrame(stores)
    stores_df.to_csv('data/output/stores.csv', index=False)


if __name__ == "__main__":
    generate_stores_schema()